### ISSUE TITLE
How to connect wam-hand skill(running remotely) to alexa-app server (running locally)?

### ISSUE THREAD

**Issue by c9zealous** [mdeyo/alexa-node-ROS#1]
When i test my skill on alexa skills kit the request is sent correctly however, when i test using voice commands using an echo im getting an error.

Is there any other way to connect the alexa skills kit (running remotely) with the alexa-app server (running locally) ?

**Comment by mdeyo** [comment]
Saw your issue! Thanks for asking. What is the error that you are getting from the echo? Is it saying that the skill is unreachable? Have you set up your Alexa app server with ssl for port 443?

I will have more time to work on helping you tonight.

**Comment by c9zealous** [comment]
Yes, I have generated a self-signed certificate as you mentioned in your `README.md` and the Alexa app server runs at port 443 locally on my Robot. I have used Bespoke Tunnel (http://docs.bespoken.tools/en/latest/commands/proxy/) to forward the local server with a public url

I ran the code like `alexa-node-ROS/examples: $ sudo bst proxy lambda server.js` , This generates a public url, which I had kept in the HTTPs end-point in the alexa skill. `server.js` is exactly same as your project. 

When, I test my skill on Alexa Skill Kit it gives proper response in the terminal server.js . However, When I use voice command through alexa it gives an incorrect sessionEndRequest error in my Terminal and on the echo says `The skill is not reachable`.

How can I establish a contact between Locally Running Alexa-App and alexa skill on the cloud ?
Also could you please let me know what Utterances and Slots did you enter in the Alexa Skill kit ?
Did you run the code locally on the Robot's computer or did you host on a domain/ subdomain, If locally then how?

**Comment by mdeyo** [comment]
Found a few issues in the newest version of the code. Hoping that the edits I just pushed help! I also added more to the readme for reference.

Once the app server is running in node, you should be able to navigate to http://localhost:8081/alexa/wam-hand and test with a simulated Echo interface.

This will allow you to test to make the the app running on the robot is working and accessible from another machine. You can also copy-paste the schema and utterances from the simulated Echo interface into your Alexa Skill kit (Echo developer page) to ensure that they match on both ends.

**Comment by c9zealous** [comment]
Thank you so much! Looks like everything works just fine.

**Comment by mdeyo** [comment]
@c9zealous  Let me know if you need any additional help with integration. I'm interested in learning more about your robot voice interface project
